name: Trigger Jenkins Build

on:
  push:
    branches: [ main ]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins via API
        run: |
          curl -X POST "$JENKINS_URL" \
            --user "$JENKINS_USER:$JENKINS_TOKEN"
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
